version: '3.4'
#Define our services.
services:
  cleanproject-service: #name of the container which will be displayed.
    image: clean-application:1.01 #name of the image we are going to create an instance of. If it can't find the image, it will use the 'build' to find the dockerfile and create an image with the specifed 'image' name.
    ports: #This is the equivelent of -p for mapping our external port:container port
     - "1010:80"
    build: #required in case we can't find our image. This will build and create our image
      context: . #refers to the filepath of the compose file. '.' specifies this directory
      dockerfile: CleanProject/Dockerfile #refers to the path of the dockerfile which is required if we need to build an image if we can't find it
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
  cleanproject-database-server:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
     - "8002:1433"
    environment:
     - ACCEPT_EULA=y
     - SA_PASSWORD=CApricorn5
     - TrustServerCertificate=true
