version: '3.4'

services:
  cleanproject-service:
    image: clean-application:dev
    container_name: CleanProject.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CleanProject.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_cleanproject-service$
    volumes:
      - /Users/sahilramanuj/Projects/CleanProject/CleanProject:/app
      - /Users/sahilramanuj/Projects/CleanProject:/src
      - /Users/sahilramanuj/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_cleanproject-service$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_cleanproject-service$ \"/app/bin/Debug/net6.0/CleanProject.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true