name: PR CI Check

on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr-build: 
    name: Checks Build and Test
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore Dependancies 
      run: dotnet restore CleanProject.sln

    - name: Build App 
      run: dotnet publish ./CleanProject/CleanProject.API.csproj -c Release -o ./publish 