name: my custom worfklow to run

on: 
  workflow_dispatch:

jobs:
  helloworld: 
    name: print hello world
    runs-on: ubuntu-latest 
    
    steps:
    - name: printstuff 
      run: echo "hello world"


