name: Shared Deployment Workflow

on:
  workflow_call:
    inputs:
      ecr-repository:
        required: true
        type: string
      ecs-cluster: 
        required: true
        type: string
      ecs-service:
        required: true
        type: string
      ecs-task-definition_path: 
        required: true
        type: string
      ecs-container-name:
        required: true
        type: string
      ecs-container-image:
        required: true
        type: string

jobs:
  deploy-ecs:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      run: |
        echo access - ${{ secrets.AWS_ACCESS_KEY_ID }}
        echo task path - ${{ inputs.ecs-task-definition-path }}
        echo ecs container name - ${{ inputs.ecs-container-name }}
        echo container image - ${{inputs.ecs-container-image}}